#!/bin/bash
#
# Description of Script TODO(you) do this
#
# MIT License
#
# Copyright (c) 2026 HumberASV
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Script Constants >>>

VERSION=0.0.0 #TODO(you): Change this to match

# Colors for stdout
PRIMARY=$(tput sgr0)
RED=$(tput setaf 9)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
ORANGE=$(tput setaf 202)
BLUE=$(tput setaf 4)
BOLD=$(tput bold)

# <<< Script Constants

# Script Arguments >>>

VERBOSE=0
DRY_RUN=0

# <<< Script Arguments

# <<< Utility Functions

#######################################
# Logs to stdout if $VERBOSE true
# Globals:
# VERBOSE
# GREEN
# BOLD
# PRIMARY
# Arguments:
#   $* - the msg
# Returns:
# Nothing
#######################################
log() {
    if [[ "$VERBOSE" -eq 1 ]]; then
        echo "${GREEN}${BOLD}[INFO] ${PRIMARY}$*"
    fi
}

#######################################
# Prints Error; does not exit
# Globals:
# RED
# BOLD
# PRIMARY
# Arguments:
#   $* - the msg
# Returns:
# Nothing
#######################################
error() {
    echo "${RED}${BOLD}[ERROR] ${PRIMARY}$*" >&2
}

#######################################
# Prints warning
# Globals:
# ORANGE
# BOLD
# PRIMARY
# Arguments:
#   $* - the msg
# Returns:
# Nothing
#######################################
warn() {
    echo "${ORANGE}${BOLD}[WARN] ${PRIMARY}$*" >&2
}

#######################################
# Runs a command unless $DRY_RUN is true then it prints it to sdtout
# Globals:
# YELLOW
# BOLD
# PRIMARY
# Arguments:
#   $1 - the command
# Returns:
# Either the string of the command or executes the command with eval
#######################################
run() {
    if [[ "$DRY_RUN" -eq 1 ]]; then
        echo "${YELLOW}${BOLD}[DRY RUN] ${PRIMARY} $*"
    else
        eval "$@"
    fi
}

#######################################
# Checks if the required command exists and exits if not
# Globals:
# BLUE
# PRIMARY
# Arguments:
#   $1 - the command
# Returns:
# Nothing, exits if commmand is missing
#######################################
require_command() {
    command -v "$1" >/dev/null 2>&1 || {
        error Missing required command: ${BLUE} "$1" ${PRIMARY} Please install and retry.
        exit 1
    }
}

#######################################
# Asks on stdout using read for confirmation
# Globals:
# BOLD
# PRIMARY
# REPLY
# Arguments:
#   $1 - prompt string
# Returns:
#   0 if yes
#   1 if no
#######################################
confirm() {
    local prompt="${1:-Are you sure?}"
    local reply
    while true; do
        read -n 1 -r -p "${prompt} ${BOLD}[y/n]${PRIMARY}: "
        echo 
        case "$REPLY" in
            [Yy]) return 0;;
            [Nn]) return 1;;
            *) printf "Please enter y or n.\n";;
        esac
    done
}

# MAIN FUNCTIONS >>>

usage() {
    cat << EOF
Usage: $(basename "$0") [options]

Options:
    -h, --help      Show help
    -v, --verbose   Enable verbose mode
    --dry-run       Do not execute changes
    --version       print version
EOF
}

#######################################
# Parses arguments
# Globals:
# VERBOSE
# DRY_RUN
# VERSION
# Arguments:
#   $@ Arguments to parse
# Returns:
# Nothing
#######################################
parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -v|--verbose)
                VERBOSE=1
                shift
                ;;
            --dry-run)
                DRY_RUN=1
                shift
                ;;
            -h|help)
                usage
                exit 0
                ;;
            --version)
                echo v"$VERSION"
                exit 0
                ;;
            *)
                error "Unknown option $1"
                exit 1
                ;;
        esac
    done
}

parse_arguments $@